data_dir: data/processed/v2
data_path: data/preprocessed/landmarks_metadata_v3_training.csv

frame_interval_fn: random_timestamps
interval: 15

# the order and presence different landmarks types in input vector
landmark_types: [pose, right_hand, left_hand]

# the order of features computation:
# [features, landmarks] will result in [**pose_angles, **righ_hand_angles, **left_hand_angles, **pose_distances, ...]
# [landmarks, features] will result in [**pose_angles, **pose_distances, **right_hand_angles, **right_hand_distances, ...]
ordering: [features, landmarks]