defaults:
  - _self_
  - optimizer: adam
  - scheduler: cyclic
  - model: transformer
  - dataset: dataset
  - training: training
  - features: 
    - angles
    - differences
    - distances
  - augmentation: base_augs

# Hydra configuration
hydra:
  run:
    dir: modelling/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: false

general: 
  enable_saving: true  # Set to false to disable all saving
  experiment_name: null  # Optional name to include in filenames
  author: null  # Optional metadata
  log_path: 
  save_dir: 