num_epochs: 300
train_batch_size: 64
val_batch_size: 256
patience: 50
lr: 1e-4

device: cuda

type: cross_validation
k_folds: 5

# Resume training parameters
resume: false  # Whether to resume training from checkpoint
run_dir: null  # Directory containing training run to resume from (e.g. modelling/runs/20240603_010104_LSTM_experiment1)