positions:
  class_name: models.landmark.features.base_estimator.LandmarkEstimator
  pose:
    # face 0-10
    nose: 0
    left_eye_inner: 1
    left_eye: 2
    left_eye_outer: 3
    right_eye_inner: 4
    right_eye: 5
    right_eye_outer: 6
    left_ear: 7
    right_ear: 8
    mouth_left: 9
    mouth_right: 10
    # --- upper body 11-22 ---
    left_shoulder: 11
    right_shoulder: 12
    left_elbow: 13
    right_elbow: 14
    left_wrist: 15
    right_wrist: 16
    left_pinky: 17
    right_pinky: 18
    left_index: 19
    right_index: 20
    left_thumb: 21
    right_thumb: 22
    # --- lower body 23-32 ---
    # left_hip: 23
    # right_hip: 24
    # left_knee: 25
    # right_knee: 26
    # left_ankle: 27
    # right_ankle: 28
    # left_heel: 29
    # right_heel: 30
    # left_foot_index: 31
    # right_foot_index: 32

  hand:
    # --- hand info ---
    # - cmc is the thumb joint in your palm to the wrist
    # - mcp is the finger/thumb joint connecting a finger/thumb to the palm
    # - ip is the thumb joint in the middle of the thumb
    # - pip is the joint in the middle of the finger closest to the palm
    # - dip is the joint in the middle of the finger closest to the tip
    # - tip is the tip of the finger
    wrist: 0
    thumb_cmc: 1
    thumb_mcp: 2
    thumb_ip: 3
    thumb_tip: 4
    index_finger_mcp: 5
    index_finger_pip: 6
    index_finger_dip: 7
    index_finger_tip: 8
    middle_finger_mcp: 9
    middle_finger_pip: 10
    middle_finger_dip: 11
    ring_finger_mcp: 13
    ring_finger_pip: 14
    ring_finger_dip: 15
    pinky_mcp: 16
    pinky_pip: 18
    pinky_dip: 19
    pinky_tip: 20 

  computation_type: null
  mode: 2D