 # Training & Model Configuration
defaults:
  - _self_
  - optimizer: adamw
  - scheduler: plateau
  - model: lstm
  - dataset: dataset
  - training: training
  - features: 
    - positions
    - angles
    - differences
    - distances
    - metadata
  - augmentation: base_augs

# Training Run Folder Name
general: 
  experiment_name: null  # Optional text to include in run folder name
  author: null  # Optional text to include in run folder name

# Hydra configuration: These are all to disable Hydra's default logging setup
hydra:
  run:
    dir: .
  output_subdir: null  # Disable saving Hydra config files
  job:
    chdir: false  # Prevent changing working directory
  job_logging:
    disabled: true  # Disable Hydra's automatic logging setup
  hydra_logging:
    disabled: true  # Disable Hydra's automatic logging setup