defaults:
  - _self_
  - optimizer: adamw
  - scheduler: plateau
  - model: lstm
  - dataset: dataset
  - training: training
  - features: 
    - positions
    - angles
    - differences
    - distances
    - metadata
  - augmentation: base_augs

# Hydra configuration
hydra:
  output_subdir: null  # Disable saving Hydra config files

general: 
  experiment_name: null  # Optional name to include in filenames
  author: null  # Optional metadata