data_dir: /home/ana/Projects/Omdena/HealthSignLangBrazil/SaoPauloBrazilChapter_BrazilianSignLanguage/data/processed/v2
data_path: /home/ana/Projects/Omdena/HealthSignLangBrazil/SaoPauloBrazilChapter_BrazilianSignLanguage/data/processed/target_dataset_video_metadata.csv

landmark_order: [angles, distances, differences]
landmark_feature_list: [angles, distances,differences]
landmark_types: ["pose", "right_hand", "left_hand"]

frame_interval_fn: random_timestamps
interval: 15

distance_type: shifted_dist
angle_type: func
diff_type: normalized_diff

distance_mode: 3D
angle_mode: 3D
diff_mode: 3D

hand_angle_triplets: /home/ana/Projects/Omdena/HealthSignLangBrazil/SaoPauloBrazilChapter_BrazilianSignLanguage/code/models/landmark/dataset/configs/hand_angles.yaml
pose_angle_triplets: /home/ana/Projects/Omdena/HealthSignLangBrazil/SaoPauloBrazilChapter_BrazilianSignLanguage/code/models/landmark/dataset/configs/pose_angles.yaml

hand_distance_pairs: /home/ana/Projects/Omdena/HealthSignLangBrazil/SaoPauloBrazilChapter_BrazilianSignLanguage/code/models/landmark/dataset/configs/hand_distances.yaml
pose_distance_pairs: /home/ana/Projects/Omdena/HealthSignLangBrazil/SaoPauloBrazilChapter_BrazilianSignLanguage/code/models/landmark/dataset/configs/pose_distances.yaml

hand_differences: /home/ana/Projects/Omdena/HealthSignLangBrazil/SaoPauloBrazilChapter_BrazilianSignLanguage/code/models/landmark/dataset/configs/hand_differences.yaml
pose_differences: /home/ana/Projects/Omdena/HealthSignLangBrazil/SaoPauloBrazilChapter_BrazilianSignLanguage/code/models/landmark/dataset/configs/pose_distances.yaml