data_dir: /home/ana/Projects/Omdena/HealthSignLangBrazil/SaoPauloBrazilChapter_BrazilianSignLanguage/data/processed/v2
data_path: /home/ana/Projects/Omdena/HealthSignLangBrazil/SaoPauloBrazilChapter_BrazilianSignLanguage/data/preprocessed/preprocessed_metadata_v2.csv

landmark_features: 
  angles: [pose, right_hand, left_hand]
  distances: [pose, right_hand, left_hand]
  differences: [pose, right_hand, left_hand]

landmark_types: [pose, right_hand, left_hand]

frame_interval_fn: uniform_intervals
interval: 100

feature_computation_types: 
  distances: shifted_dist
  angles: func
  differences: normalized_diff

feature_modes:
  distances: 3D
  angles: 3D
  differences: 3D

hand_angle_triplets: /home/ana/Projects/Omdena/HealthSignLangBrazil/SaoPauloBrazilChapter_BrazilianSignLanguage/code/models/landmark/dataset/configs/hand_angles.yaml
pose_angle_triplets: /home/ana/Projects/Omdena/HealthSignLangBrazil/SaoPauloBrazilChapter_BrazilianSignLanguage/code/models/landmark/dataset/configs/pose_angles.yaml

hand_distance_pairs: /home/ana/Projects/Omdena/HealthSignLangBrazil/SaoPauloBrazilChapter_BrazilianSignLanguage/code/models/landmark/dataset/configs/hand_distances.yaml
pose_distance_pairs: /home/ana/Projects/Omdena/HealthSignLangBrazil/SaoPauloBrazilChapter_BrazilianSignLanguage/code/models/landmark/dataset/configs/pose_distances.yaml

hand_differences: /home/ana/Projects/Omdena/HealthSignLangBrazil/SaoPauloBrazilChapter_BrazilianSignLanguage/code/models/landmark/dataset/configs/hand_differences.yaml
pose_differences: /home/ana/Projects/Omdena/HealthSignLangBrazil/SaoPauloBrazilChapter_BrazilianSignLanguage/code/models/landmark/dataset/configs/pose_differences.yaml