left_shoulder_angle: [11, 13, 15]   # shoulder → elbow → wrist
right_shoulder_angle: [12, 14, 16]

left_elbow_angle: [13, 15, 19]      # elbow → wrist → index
right_elbow_angle: [14, 16, 20]

shoulder_neck_tilt: [11, 0, 12]     # left_shoulder → nose → right_shoulder

left_arm_curve: [11, 15, 19]
right_arm_curve: [12, 16, 20]
