wrist_distance: [15, 16]
index_distance: [19, 20]
thumb_distance: [21, 22]

left_hand_to_head: [15, 0]
right_hand_to_head: [16, 0]

left_hand_to_left_shoulder: [15, 11]
right_hand_to_right_shoulder: [16, 12]

left_hand_to_right_shoulder: [15, 12]
right_hand_to_left_shoulder: [16, 11]

shoulder_width: [11, 12]
hip_width: [23, 24]

shoulder_to_hip_left: [11, 23]
shoulder_to_hip_right: [12, 24]
