right_shoulder_angle: [12, 14, 16]
right_elbow_to_thumb_angle: [14, 16, 18]
right_wrist_spread_angle: [18, 16, 22]
right_shoulder_tilt_angle: [14, 12, 24]

left_shoulder_angle: [11, 13, 15]
left_elbow_to_thumb_angle: [13, 15, 17]
left_wrist_spread_angle: [17, 15, 21]
left_shoulder_tilt_angle: [13, 11, 23]  

left_elbow_angle: [13, 15, 19]      
right_elbow_angle: [14, 16, 20]

shoulder_neck_tilt: [11, 0, 12]   

left_arm_curve: [11, 15, 19]
right_arm_curve: [12, 16, 20]
