# Version of the preprocessed landmark data to use
data_version: "v4"

# Frame sampling for training split
frame_sampling_train:
  enabled: true
  method: multiple_uniform
  params:
    frames_per_sample: 20
    num_samples_limit: 5
    replacement_rate: 0.2
    include_remaining: True

# Frame sampling for validation/test splits
# -- currently, the code in train.py means that the frame_sampling_train settings are used for validation as well --
frame_sampling_test:
  method: multiple_uniform  # Deterministic sampling for consistent evaluation
  params:
    frames_per_sample: 20
    num_samples_limit: 5 
    replacement_rate: 0.2
    include_remaining: True

# the order and presence different landmarks types in input vector
landmark_types: [pose, right_hand, left_hand]

# the order of features computation:
# [features, landmark_types] will result in [**pose_angles, **right_hand_angles, **left_hand_angles, **pose_distances, ...]
# [landmark_types, features] will result in [**pose_angles, **pose_distances, **right_hand_angles, **right_hand_distances, ...]
ordering: [features, landmark_types]

# Base paths configuration
paths:
  preprocessed_base: "data/preprocessed"
  metadata_base: "modelling/metadata"
  logs_base: "modelling/runs"  # New consolidated location for all run artifacts
  landmark_arrays_base: "modelling/landmark_arrays"