class_name: model.models.transformers.TransformerClassifier
params:
  # input_size: 215 # Calculated automatically in trainer.py
  num_classes: 25
  d_model: 128
  nhead: 8
  num_layers: 2
  dim_feedforward: 256
  dropout: 0.1